"""CatalogoFontes e Status

Revision ID: e75126a31a9d
Revises: 
Create Date: 2026-04-18 15:49:52.489780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e75126a31a9d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogo_fontes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('orgao_emissor', sa.String(length=100), nullable=False),
    sa.Column('status_processamento', sa.String(length=50), server_default='APROVADO', nullable=False),
    sa.Column('caminho_temporario', sa.Text(), nullable=True),
    sa.Column('tipo_documento', sa.String(length=50), nullable=False),
    sa.Column('categoria_agronomica', sa.String(length=100), nullable=False),
    sa.Column('data_publicacao', sa.Date(), nullable=True),
    sa.Column('url_ou_caminho_original', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalogo_fontes_categoria_agronomica'), 'catalogo_fontes', ['categoria_agronomica'], unique=False)
    op.create_index(op.f('ix_catalogo_fontes_id'), 'catalogo_fontes', ['id'], unique=False)
    op.create_index(op.f('ix_catalogo_fontes_titulo'), 'catalogo_fontes', ['titulo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_catalogo_fontes_titulo'), table_name='catalogo_fontes')
    op.drop_index(op.f('ix_catalogo_fontes_id'), table_name='catalogo_fontes')
    op.drop_index(op.f('ix_catalogo_fontes_categoria_agronomica'), table_name='catalogo_fontes')
    op.drop_table('catalogo_fontes')
    # ### end Alembic commands ###
